Backend: VitisUnified
ClockPeriod: '5'
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    dense_0:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_0_iq:
      Precision:
        result: auto
      Trace: false
    dense_0_relu:
      Precision:
        result: auto
      Trace: false
    dense_1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_1_iq:
      Precision:
        result: auto
      Trace: false
    dense_1_relu:
      Precision:
        result: auto
      Trace: false
    dense_2:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_2_iq:
      Precision:
        result: auto
      Trace: false
    dense_2_relu:
      Precision:
        result: auto
      Trace: false
    dense_3:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_3_iq:
      Precision:
        result: auto
      Trace: false
    input_layer:
      Precision:
        result: auto
      Trace: false
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Distributed Arithmetic
    TraceOutput: false
IOType: io_stream
InputData: null
InputShapes:
  input_layer:
  - 16
KerasModel: !keras_model '/work/development/jettag/jettag-hgq2/Training_FixedHP/hls4ml_prj_acc=0.7590_ebops=11634_VU_DA_bitfile/keras_model.keras'
OutputDir: /work/development/jettag/jettag-hgq2/Training_FixedHP/hls4ml_prj_acc=0.7590_ebops=11634_VU_DA_bitfile
OutputPredictions: null
OutputShapes:
  layer12_out:
  - 5
Part: xck26-sfvc784-2LV-c
ProjectName: myproject
Stamp: 7a4d7cdf
Version: 1.0.0
VitisUnifiedConfig:
  Board: kv260
  Driver: python
  InputDtype: float
  OutputDtype: float
  axi_mode: axi_master
  in_stream_buf_size: 128
  out_stream_buf_size: 128
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
