<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName></userIPName>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>dense_array_ap_ufixed_64u_array_ap_fixed_13_10_5_3_0_32u_config9_s</name>
      <module_structure>Sequential</module_structure>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>layer7_out</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>data_stream</originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>512</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>layer9_out</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>res_stream</originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>416</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>11</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>5</id>
              <name>layer7_out_read</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>43</lineNumber>
              <contextFuncName>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>data_prepare_nnet_array_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_64U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>2</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>43</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>93</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>srl</implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>80</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>512</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>18</item>
            <item>19</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.83</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>6</id>
              <name>data</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>43</lineNumber>
              <contextFuncName>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>data_prepare_nnet_array_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_64U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>43</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>93</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>data</originalName>
              <rtlName>data_reg_115</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>21</item>
            <item>22</item>
            <item>24</item>
            <item>26</item>
          </oprand_edges>
          <opcode>partselect</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>7</id>
              <name>data_1</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>43</lineNumber>
              <contextFuncName>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>data_prepare_nnet_array_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_64U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>43</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>93</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>data</originalName>
              <rtlName>data_1_reg_120</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>27</item>
            <item>28</item>
            <item>30</item>
            <item>32</item>
          </oprand_edges>
          <opcode>partselect</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>data_2</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>43</lineNumber>
              <contextFuncName>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>data_prepare_nnet_array_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_64U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>data_prepare&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>43</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>93</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>data</originalName>
              <rtlName>data_2_reg_125</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>34</item>
            <item>36</item>
            <item>38</item>
          </oprand_edges>
          <opcode>partselect</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>9</id>
              <name>call_ret</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>17</lineNumber>
              <contextFuncName>dense_latency_wrapper&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>dense_latency_wrapper_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>95</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense_latency_wrapper&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s_fu_53</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>26</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>40</item>
            <item>41</item>
            <item>42</item>
            <item>43</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.71</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>10</id>
              <name>res</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>17</lineNumber>
              <contextFuncName>dense_latency_wrapper&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>dense_latency_wrapper_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>95</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense_latency_wrapper&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>res</originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>13</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>44</item>
          </oprand_edges>
          <opcode>extractvalue</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>11</id>
              <name>res_1</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>17</lineNumber>
              <contextFuncName>dense_latency_wrapper&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>dense_latency_wrapper_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>95</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense_latency_wrapper&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>17</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>res</originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>13</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>45</item>
          </oprand_edges>
          <opcode>extractvalue</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>7</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>12</id>
              <name>or_ln77_1</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>77</lineNumber>
              <contextFuncName>res_write&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>res_write_nnet_array_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_32U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>100</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>res_write&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>77</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>or_ln77_1_fu_98_p5</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>364</bitwidth>
          </Value>
          <oprand_edges>
            <count>5</count>
            <item_version>0</item_version>
            <item>47</item>
            <item>48</item>
            <item>50</item>
            <item>51</item>
            <item>53</item>
          </oprand_edges>
          <opcode>bitconcatenate</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>8</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>13</id>
              <name>zext_ln77</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>77</lineNumber>
              <contextFuncName>res_write&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>res_write_nnet_array_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_32U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>100</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>res_write&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>77</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>layer9_out_din</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>416</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>54</item>
          </oprand_edges>
          <opcode>zext</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>9</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>14</id>
              <name>layer9_out_write_ln77</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>77</lineNumber>
              <contextFuncName>res_write&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>res_write_nnet_array_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_32U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>100</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>res_write&amp;lt;nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>77</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>srl</implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>80</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>56</item>
            <item>57</item>
            <item>58</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.83</m_delay>
          <m_topoIndex>10</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>15</id>
              <name>_ln101</name>
              <fileName>firmware/nnet_utils/nnet_dense_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>101</lineNumber>
              <contextFuncName>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</contextFuncName>
              <contextNormFuncName>dense_nnet_array_ap_ufixed_8_6_ap_q_mode_0_ap_o_mode_3_0_64U_nnet_array_ap_fixed_13_10_ap_q_mode_5_ap_o_mode_3_0_32U_config9_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_latency_bitfile</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_dense_stream.h</first>
                        <second>dense&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;8, 6, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 64U&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;13, 10, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 32U&amp;gt;, config9&amp;gt;</second>
                      </first>
                      <second>101</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>11</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>9</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_14">
          <Value>
            <Obj>
              <type>2</type>
              <id>23</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>96</content>
        </item>
        <item class_id_reference="16" object_id="_15">
          <Value>
            <Obj>
              <type>2</type>
              <id>25</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>103</content>
        </item>
        <item class_id_reference="16" object_id="_16">
          <Value>
            <Obj>
              <type>2</type>
              <id>29</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>152</content>
        </item>
        <item class_id_reference="16" object_id="_17">
          <Value>
            <Obj>
              <type>2</type>
              <id>31</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>159</content>
        </item>
        <item class_id_reference="16" object_id="_18">
          <Value>
            <Obj>
              <type>2</type>
              <id>35</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>224</content>
        </item>
        <item class_id_reference="16" object_id="_19">
          <Value>
            <Obj>
              <type>2</type>
              <id>37</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>231</content>
        </item>
        <item class_id_reference="16" object_id="_20">
          <Value>
            <Obj>
              <type>2</type>
              <id>39</id>
              <name>dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>26</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:dense_latency&lt;ap_ufixed&lt;8, 6, 0, 3, 0&gt;, ap_fixed&lt;13, 10, 5, 3, 0&gt;, config9&gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_21">
          <Value>
            <Obj>
              <type>2</type>
              <id>49</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>247</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_22">
          <Value>
            <Obj>
              <type>2</type>
              <id>52</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>91</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_23">
          <Obj>
            <type>3</type>
            <id>16</id>
            <name>dense&lt;array&lt;ap_ufixed,64u&gt;,array&lt;ap_fixed&lt;13,10,5,3,0&gt;,32u&gt;,config9&gt;</name>
            <fileName></fileName>
            <fileDirectory></fileDirectory>
            <lineNumber>0</lineNumber>
            <contextFuncName></contextFuncName>
            <contextNormFuncName></contextNormFuncName>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName></originalName>
            <rtlName></rtlName>
            <control></control>
            <opType></opType>
            <implIndex></implIndex>
            <coreName></coreName>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>4294967295</coreId>
            <rtlModuleName></rtlModuleName>
          </Obj>
          <node_objs>
            <count>11</count>
            <item_version>0</item_version>
            <item>5</item>
            <item>6</item>
            <item>7</item>
            <item>8</item>
            <item>9</item>
            <item>10</item>
            <item>11</item>
            <item>12</item>
            <item>13</item>
            <item>14</item>
            <item>15</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>23</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_24">
          <id>19</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>5</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>22</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>6</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>24</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>6</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>26</id>
          <edge_type>1</edge_type>
          <source_obj>25</source_obj>
          <sink_obj>6</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>28</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>7</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>30</id>
          <edge_type>1</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>7</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>32</id>
          <edge_type>1</edge_type>
          <source_obj>31</source_obj>
          <sink_obj>7</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>34</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>8</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>36</id>
          <edge_type>1</edge_type>
          <source_obj>35</source_obj>
          <sink_obj>8</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>38</id>
          <edge_type>1</edge_type>
          <source_obj>37</source_obj>
          <sink_obj>8</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>40</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>9</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>41</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>9</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>42</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>9</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>43</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>9</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>44</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>10</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>45</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>11</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>48</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>12</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>50</id>
          <edge_type>1</edge_type>
          <source_obj>49</source_obj>
          <sink_obj>12</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>51</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>12</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>53</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>12</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>54</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>13</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>57</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>14</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>58</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>14</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_47">
        <mId>1</mId>
        <mTag>dense&lt;array&lt;ap_ufixed,64u&gt;,array&lt;ap_fixed&lt;13,10,5,3,0&gt;,32u&gt;,config9&gt;</mTag>
        <mNormTag>dense_array_ap_ufixed_64u_array_ap_fixed_13_10_5_3_0_32u_config9_s</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>16</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>1</mMinLatency>
        <mMaxLatency>1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"></mDfPipe>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_48">
      <states class_id="25" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_49">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_50">
              <id>5</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_51">
              <id>6</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_52">
              <id>7</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_53">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_54">
          <id>2</id>
          <operations>
            <count>9</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_55">
              <id>3</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_56">
              <id>4</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_57">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_58">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_59">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_60">
              <id>12</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_61">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_62">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_63">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_64">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="34" tracking_level="1" version="0" object_id="_65">
      <dp_component_resource class_id="35" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s_fu_53 (dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s)</first>
          <second class_id="37" tracking_level="0" version="0">
            <count>2</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="0" version="0">
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>91</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>ap_block_state1 ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>5</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>3</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>3</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>14</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer7_out_blk_n</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer9_out_blk_n</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>real_start</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>6</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>2</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>data_1_reg_120</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>8</second>
            </item>
          </second>
        </item>
        <item>
          <first>data_2_reg_125</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>8</second>
            </item>
          </second>
        </item>
        <item>
          <first>data_reg_115</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>8</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>8</second>
            </item>
          </second>
        </item>
        <item>
          <first>start_once_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s_fu_53</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="39" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="0" version="0">
          <first>call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s_fu_53 (dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>9</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="41" tracking_level="0" version="0">
      <count>11</count>
      <item_version>0</item_version>
      <item class_id="42" tracking_level="0" version="0">
        <first>5</first>
        <second class_id="43" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>6</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>7</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>8</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>9</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>10</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>11</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>12</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>13</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>14</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>15</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="44" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>16</first>
        <second class_id="46" tracking_level="0" version="0">
          <first>0</first>
          <second>1</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="47" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="48" tracking_level="0" version="0">
      <count>10</count>
      <item_version>0</item_version>
      <item class_id="49" tracking_level="0" version="0">
        <first>40</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
      <item>
        <first>53</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>60</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>70</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>90</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>94</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </second>
      </item>
      <item>
        <first>98</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>110</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="51" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>data_1_fu_70</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>data_2_fu_80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>data_fu_60</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>or_ln77_1_fu_98</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>res_1_fu_94</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </second>
      </item>
      <item>
        <first>res_fu_90</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>zext_ln77_fu_110</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_10_5_3_0_config9_s_fu_53</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>layer7_out_read_read_fu_40</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>write_ln77_write_fu_46</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="53" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>115</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>120</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>125</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>data_1_reg_120</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>data_2_reg_125</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>data_reg_115</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="54" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="55" tracking_level="0" version="0">
        <first>layer7_out</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>5</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>layer9_out</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>write</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>14</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>1</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
      <item>
        <first>2</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
    </port2core>
    <node2core>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>5</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
      <item>
        <first>9</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
      <item>
        <first>14</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
    </node2core>
    <sched_res class_id="-1"></sched_res>
  </syndb>
</boost_serialization>
