

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "129", "161", "167", "168", "169", "170", "171", "172", "173"],
		"CDFG" : "myproject_axi_master",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "entry_proc_U0"},
			{"ID" : "5", "Name" : "load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0"}],
		"OutputProcess" : [
			{"ID" : "161", "Name" : "store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0"}],
		"Port" : [
			{"Name" : "gmem_in0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0", "Port" : "gmem_in0"}]},
			{"Name" : "gmem_out0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "161", "SubInstance" : "store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0", "Port" : "gmem_out0"}]},
			{"Name" : "gmem_in0_ptr_input_layer", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out0_ptr_layer15_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "batch_size", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0", "Port" : "stream_in0_input_layer"},
					{"ID" : "129", "SubInstance" : "compute_U0", "Port" : "stream_in0_input_layer"}]},
			{"Name" : "stream_out0_layer15_out", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "129", "SubInstance" : "compute_U0", "Port" : "stream_out0_layer15_out"},
					{"ID" : "161", "SubInstance" : "store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0", "Port" : "stream_out0_layer15_out"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_in0_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out0_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_out0_ptr_layer15_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out0_ptr_layer15_out_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["161"], "DependentChan" : "167", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "gmem_out0_ptr_layer15_out_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0", "Parent" : "0", "Child" : ["6"],
		"CDFG" : "load_input_float_array_ap_fixed_11_7_0_3_0_60u_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_in0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in0_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90", "Port" : "gmem_in0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "batch_size", "Type" : "None", "Direction" : "I"},
			{"Name" : "batch_size_c1", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["129"], "DependentChan" : "168", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_c1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["129"], "DependentChan" : "169", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90", "Port" : "stream_in0_input_layer", "Inst_start_state" : "10", "Inst_end_state" : "11"}]}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90", "Parent" : "5", "Child" : ["7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128"],
		"CDFG" : "load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "batch_size", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_in0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln13", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "stream_in0_input_layer_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_13_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "60", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage4", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage4_subdone", "QuitState" : "ap_ST_fsm_pp0_stage4", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage4_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.fpext_32ns_64_2_no_dsp_1_U3", "Parent" : "6"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U4", "Parent" : "6"},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U5", "Parent" : "6"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U6", "Parent" : "6"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U7", "Parent" : "6"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U8", "Parent" : "6"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U9", "Parent" : "6"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U10", "Parent" : "6"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U11", "Parent" : "6"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U12", "Parent" : "6"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U13", "Parent" : "6"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U14", "Parent" : "6"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U15", "Parent" : "6"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U16", "Parent" : "6"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U17", "Parent" : "6"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U18", "Parent" : "6"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U19", "Parent" : "6"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U20", "Parent" : "6"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U21", "Parent" : "6"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U22", "Parent" : "6"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U23", "Parent" : "6"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U24", "Parent" : "6"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U25", "Parent" : "6"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U26", "Parent" : "6"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U27", "Parent" : "6"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U28", "Parent" : "6"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U29", "Parent" : "6"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U30", "Parent" : "6"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U31", "Parent" : "6"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U32", "Parent" : "6"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U33", "Parent" : "6"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U34", "Parent" : "6"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U35", "Parent" : "6"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U36", "Parent" : "6"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U37", "Parent" : "6"},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U38", "Parent" : "6"},
	{"ID" : "43", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U39", "Parent" : "6"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U40", "Parent" : "6"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U41", "Parent" : "6"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U42", "Parent" : "6"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U43", "Parent" : "6"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U44", "Parent" : "6"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U45", "Parent" : "6"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U46", "Parent" : "6"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U47", "Parent" : "6"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U48", "Parent" : "6"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U49", "Parent" : "6"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U50", "Parent" : "6"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U51", "Parent" : "6"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U52", "Parent" : "6"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U53", "Parent" : "6"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U54", "Parent" : "6"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U55", "Parent" : "6"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U56", "Parent" : "6"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U57", "Parent" : "6"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U58", "Parent" : "6"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U59", "Parent" : "6"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U60", "Parent" : "6"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U61", "Parent" : "6"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U62", "Parent" : "6"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U63", "Parent" : "6"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U64", "Parent" : "6"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U65", "Parent" : "6"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U66", "Parent" : "6"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U67", "Parent" : "6"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U68", "Parent" : "6"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U69", "Parent" : "6"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U70", "Parent" : "6"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U71", "Parent" : "6"},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U72", "Parent" : "6"},
	{"ID" : "77", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U73", "Parent" : "6"},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U74", "Parent" : "6"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U75", "Parent" : "6"},
	{"ID" : "80", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U76", "Parent" : "6"},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U77", "Parent" : "6"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U78", "Parent" : "6"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U79", "Parent" : "6"},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U80", "Parent" : "6"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U81", "Parent" : "6"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U82", "Parent" : "6"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U83", "Parent" : "6"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U84", "Parent" : "6"},
	{"ID" : "89", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U85", "Parent" : "6"},
	{"ID" : "90", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U86", "Parent" : "6"},
	{"ID" : "91", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U87", "Parent" : "6"},
	{"ID" : "92", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U88", "Parent" : "6"},
	{"ID" : "93", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U89", "Parent" : "6"},
	{"ID" : "94", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U90", "Parent" : "6"},
	{"ID" : "95", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U91", "Parent" : "6"},
	{"ID" : "96", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U92", "Parent" : "6"},
	{"ID" : "97", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U93", "Parent" : "6"},
	{"ID" : "98", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U94", "Parent" : "6"},
	{"ID" : "99", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U95", "Parent" : "6"},
	{"ID" : "100", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U96", "Parent" : "6"},
	{"ID" : "101", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U97", "Parent" : "6"},
	{"ID" : "102", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U98", "Parent" : "6"},
	{"ID" : "103", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U99", "Parent" : "6"},
	{"ID" : "104", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U100", "Parent" : "6"},
	{"ID" : "105", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U101", "Parent" : "6"},
	{"ID" : "106", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U102", "Parent" : "6"},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U103", "Parent" : "6"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U104", "Parent" : "6"},
	{"ID" : "109", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U105", "Parent" : "6"},
	{"ID" : "110", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U106", "Parent" : "6"},
	{"ID" : "111", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U107", "Parent" : "6"},
	{"ID" : "112", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U108", "Parent" : "6"},
	{"ID" : "113", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U109", "Parent" : "6"},
	{"ID" : "114", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U110", "Parent" : "6"},
	{"ID" : "115", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U111", "Parent" : "6"},
	{"ID" : "116", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U112", "Parent" : "6"},
	{"ID" : "117", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U113", "Parent" : "6"},
	{"ID" : "118", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U114", "Parent" : "6"},
	{"ID" : "119", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U115", "Parent" : "6"},
	{"ID" : "120", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U116", "Parent" : "6"},
	{"ID" : "121", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U117", "Parent" : "6"},
	{"ID" : "122", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U118", "Parent" : "6"},
	{"ID" : "123", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U119", "Parent" : "6"},
	{"ID" : "124", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U120", "Parent" : "6"},
	{"ID" : "125", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U121", "Parent" : "6"},
	{"ID" : "126", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.bitselect_1ns_54ns_6ns_1_1_1_U122", "Parent" : "6"},
	{"ID" : "127", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.sparsemux_9_3_11_1_1_U123", "Parent" : "6"},
	{"ID" : "128", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_7_0_3_0_60u_U0.grp_load_input_float_array_ap_fixed_60u_Pipeline_VITIS_LOOP_13_1_fu_90.flow_control_loop_pipe_sequential_init_U", "Parent" : "6"},
	{"ID" : "129", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0", "Parent" : "0", "Child" : ["130"],
		"CDFG" : "compute",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "5",
		"StartFifo" : "start_for_compute_U0_U",
		"Port" : [
			{"Name" : "batch_size", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "168", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "batch_size_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["161"], "DependentChan" : "170", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "169", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "130", "SubInstance" : "grp_myproject_fu_62", "Port" : "stream_in0_input_layer", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_out0_layer15_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["161"], "DependentChan" : "171", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "130", "SubInstance" : "grp_myproject_fu_62", "Port" : "stream_out0_layer15_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_42_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "130", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62", "Parent" : "129", "Child" : ["131", "133", "134", "136", "137", "139", "140", "142", "143", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160"],
		"CDFG" : "myproject",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "21", "EstimateLatencyMax" : "21",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "131", "Name" : "dense_array_ap_fixed_60u_array_ap_fixed_16_13_5_3_0_128u_config3_U0"}],
		"OutputProcess" : [
			{"ID" : "143", "Name" : "dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_U0"}],
		"Port" : [
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "131", "SubInstance" : "dense_array_ap_fixed_60u_array_ap_fixed_16_13_5_3_0_128u_config3_U0", "Port" : "stream_in0_input_layer"}]},
			{"Name" : "stream_out0_layer15_out", "Type" : "Fifo", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "143", "SubInstance" : "dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_U0", "Port" : "stream_out0_layer15_out"}]}]},
	{"ID" : "131", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_60u_array_ap_fixed_16_13_5_3_0_128u_config3_U0", "Parent" : "130", "Child" : ["132"],
		"CDFG" : "dense_array_ap_fixed_60u_array_ap_fixed_16_13_5_3_0_128u_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "layer3_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["133"], "DependentChan" : "145", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "stream_in0_input_layer_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "132", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_60u_array_ap_fixed_16_13_5_3_0_128u_config3_U0.grp_dense_latency_ap_fixed_11_7_0_3_0_ap_fixed_16_13_5_3_0_config3_s_fu_133", "Parent" : "131",
		"CDFG" : "dense_latency_ap_fixed_11_7_0_3_0_ap_fixed_16_13_5_3_0_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_32_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_33_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_36_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_37_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_38_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_39_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_40_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_41_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_43_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_49_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_50_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_51_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_52_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_53_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_55_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_56_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_57_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_58_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_59_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "133", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_128u_array_ap_ufixed_8_6_0_3_0_128u_relu_config4_U0", "Parent" : "130",
		"CDFG" : "relu_array_ap_fixed_128u_array_ap_ufixed_8_6_0_3_0_128u_relu_config4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "131",
		"StartFifo" : "start_for_relu_array_ap_fixed_128u_array_ap_ufixed_8_6_0_3_0_128u_relu_configbkb_U",
		"Port" : [
			{"Name" : "layer3_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["131"], "DependentChan" : "145", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer4_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["134"], "DependentChan" : "146", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer4_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "134", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_128u_array_ap_fixed_15_12_5_3_0_64u_config6_U0", "Parent" : "130", "Child" : ["135"],
		"CDFG" : "dense_array_ap_ufixed_128u_array_ap_fixed_15_12_5_3_0_64u_config6_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "133",
		"StartFifo" : "start_for_dense_array_ap_ufixed_128u_array_ap_fixed_15_12_5_3_0_64u_config6_U0_U",
		"Port" : [
			{"Name" : "layer4_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["133"], "DependentChan" : "146", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer6_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["136"], "DependentChan" : "147", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer6_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "135", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_128u_array_ap_fixed_15_12_5_3_0_64u_config6_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_15_12_5_3_0_config6_s_fu_117", "Parent" : "134",
		"CDFG" : "dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_15_12_5_3_0_config6_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_39_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_51_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_55_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_70_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_71_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_87_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_88_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_92_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_96_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_99_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_104_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_114_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_120_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_122_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_124_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "136", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_64u_array_ap_ufixed_8_6_0_3_0_64u_relu_config7_U0", "Parent" : "130",
		"CDFG" : "relu_array_ap_fixed_64u_array_ap_ufixed_8_6_0_3_0_64u_relu_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "134",
		"StartFifo" : "start_for_relu_array_ap_fixed_64u_array_ap_ufixed_8_6_0_3_0_64u_relu_config7_U0_U",
		"Port" : [
			{"Name" : "layer6_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["134"], "DependentChan" : "147", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer6_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer7_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["137"], "DependentChan" : "148", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer7_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "137", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_64u_array_ap_fixed_15_12_5_3_0_32u_config9_U0", "Parent" : "130", "Child" : ["138"],
		"CDFG" : "dense_array_ap_ufixed_64u_array_ap_fixed_15_12_5_3_0_32u_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "136",
		"StartFifo" : "start_for_dense_array_ap_ufixed_64u_array_ap_fixed_15_12_5_3_0_32u_config9_U0_U",
		"Port" : [
			{"Name" : "layer7_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["136"], "DependentChan" : "148", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer7_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer9_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["139"], "DependentChan" : "149", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer9_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "138", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_64u_array_ap_fixed_15_12_5_3_0_32u_config9_U0.call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_15_12_5_3_0_config9_s_fu_85", "Parent" : "137",
		"CDFG" : "dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_15_12_5_3_0_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_42_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_56_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "139", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10_U0", "Parent" : "130",
		"CDFG" : "relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "137",
		"StartFifo" : "start_for_relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10cud_U",
		"Port" : [
			{"Name" : "layer9_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["137"], "DependentChan" : "149", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer9_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer10_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["140"], "DependentChan" : "150", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer10_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "140", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_13_9_5_3_0_16u_config12_U0", "Parent" : "130", "Child" : ["141"],
		"CDFG" : "dense_array_ap_ufixed_32u_array_ap_fixed_13_9_5_3_0_16u_config12_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "139",
		"StartFifo" : "start_for_dense_array_ap_ufixed_32u_array_ap_fixed_13_9_5_3_0_16u_config12_U0_U",
		"Port" : [
			{"Name" : "layer10_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["139"], "DependentChan" : "150", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer10_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer12_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["142"], "DependentChan" : "151", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer12_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "141", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_13_9_5_3_0_16u_config12_U0.call_ret_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_9_5_3_0_config12_s_fu_57", "Parent" : "140",
		"CDFG" : "dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_13_9_5_3_0_config12_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "142", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_16u_array_ap_ufixed_8_5_0_3_0_16u_relu_config13_U0", "Parent" : "130",
		"CDFG" : "relu_array_ap_fixed_16u_array_ap_ufixed_8_5_0_3_0_16u_relu_config13_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "140",
		"StartFifo" : "start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_5_0_3_0_16u_relu_config13dEe_U",
		"Port" : [
			{"Name" : "layer12_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["140"], "DependentChan" : "151", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer12_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer13_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["143"], "DependentChan" : "152", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer13_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "143", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_U0", "Parent" : "130", "Child" : ["144"],
		"CDFG" : "dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "142",
		"StartFifo" : "start_for_dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_U0_U",
		"Port" : [
			{"Name" : "layer13_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["142"], "DependentChan" : "152", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer13_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_out0_layer15_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "stream_out0_layer15_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "144", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_U0.call_ret_i_dense_latency_ap_ufixed_8_5_0_3_0_ap_fixed_16_8_5_3_0_config15_s_fu_53", "Parent" : "143",
		"CDFG" : "dense_latency_ap_ufixed_8_5_0_3_0_ap_fixed_16_8_5_3_0_config15_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "145", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer3_out_U", "Parent" : "130"},
	{"ID" : "146", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer4_out_U", "Parent" : "130"},
	{"ID" : "147", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer6_out_U", "Parent" : "130"},
	{"ID" : "148", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer7_out_U", "Parent" : "130"},
	{"ID" : "149", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer9_out_U", "Parent" : "130"},
	{"ID" : "150", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer10_out_U", "Parent" : "130"},
	{"ID" : "151", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer12_out_U", "Parent" : "130"},
	{"ID" : "152", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer13_out_U", "Parent" : "130"},
	{"ID" : "153", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_128u_array_ap_ufixed_8_6_0_3_0_128u_relu_configbkb_U", "Parent" : "130"},
	{"ID" : "154", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_128u_array_ap_fixed_15_12_5_3_0_64u_config6_U0_U", "Parent" : "130"},
	{"ID" : "155", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_64u_array_ap_ufixed_8_6_0_3_0_64u_relu_config7_U0_U", "Parent" : "130"},
	{"ID" : "156", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_64u_array_ap_fixed_15_12_5_3_0_32u_config9_U0_U", "Parent" : "130"},
	{"ID" : "157", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10cud_U", "Parent" : "130"},
	{"ID" : "158", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_32u_array_ap_fixed_13_9_5_3_0_16u_config12_U0_U", "Parent" : "130"},
	{"ID" : "159", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_5_0_3_0_16u_relu_config13dEe_U", "Parent" : "130"},
	{"ID" : "160", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_16u_array_ap_fixed_16_8_5_3_0_3u_config15_U0_U", "Parent" : "130"},
	{"ID" : "161", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0", "Parent" : "0", "Child" : ["162"],
		"CDFG" : "store_result_float_array_ap_fixed_16_8_5_3_0_3u_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "4",
		"StartFifo" : "start_for_store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0_U",
		"Port" : [
			{"Name" : "gmem_out0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out0_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_out0_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "162", "SubInstance" : "grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81", "Port" : "gmem_out0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["4"], "DependentChan" : "167", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "batch_size", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["129"], "DependentChan" : "170", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_out0_layer15_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["129"], "DependentChan" : "171", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "162", "SubInstance" : "grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81", "Port" : "stream_out0_layer15_out", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "162", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0.grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81", "Parent" : "161", "Child" : ["163", "164", "165", "166"],
		"CDFG" : "store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "batch_size_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out0_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln29", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_out0_layer15_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "stream_out0_layer15_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_29_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "163", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0.grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_16_16_1_1_U252", "Parent" : "162"},
	{"ID" : "164", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0.grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_16_16_1_1_U253", "Parent" : "162"},
	{"ID" : "165", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0.grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_16_16_1_1_U254", "Parent" : "162"},
	{"ID" : "166", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0.grp_store_result_float_array_ap_fixed_3u_Pipeline_VITIS_LOOP_29_1_fu_81.flow_control_loop_pipe_sequential_init_U", "Parent" : "162"},
	{"ID" : "167", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out0_ptr_layer15_out_c_U", "Parent" : "0"},
	{"ID" : "168", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.batch_size_c1_U", "Parent" : "0"},
	{"ID" : "169", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.stream_in0_input_layer_U", "Parent" : "0"},
	{"ID" : "170", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.batch_size_c_U", "Parent" : "0"},
	{"ID" : "171", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.stream_out0_layer15_out_U", "Parent" : "0"},
	{"ID" : "172", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_store_result_float_array_ap_fixed_16_8_5_3_0_3u_U0_U", "Parent" : "0"},
	{"ID" : "173", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_U0_U", "Parent" : "0"}]}
