Backend: VitisUnified
ClockPeriod: 5ns
ClockUncertainty: 12.5%
HLSConfig:
  Model:
    BitExact: null
    Precision: fixed<16,6>
    ReuseFactor: 1
IOType: io_stream
InputData: /workspace/HLS4ML_testbench_KV260/development/testmodel/x_test.npy
InputShapes:
  linput:
  - 16
KerasModel: !keras_model '/workspace/HLS4ML_testbench_KV260/development/testmodel/2/hls4ml_prj_VitisUnifiedKV260_2023.2/keras_model.keras'
OutputDir: /workspace/HLS4ML_testbench_KV260/development/testmodel/2/hls4ml_prj_VitisUnifiedKV260_2023.2
OutputPredictions: /workspace/HLS4ML_testbench_KV260/development/testmodel/y_test.npy
OutputShapes:
  layer5_out:
  - 5
Part: xck26-sfvc784-2LV-c
ProjectName: myproject
Stamp: b1305c1f
Version: 1.0.0
VitisUnifiedConfig:
  Board: kv260
  Driver: python
  InputDtype: float
  OutputDtype: float
  axi_mode: axi_master
  in_stream_buf_size: 128
  out_stream_buf_size: 128
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
