

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3"],
		"CDFG" : "hgq2_1_hls4ml_prj_Vitis_da4ml",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "6", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_layer", "Type" : "Vld", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "input_layer_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer13_out_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_4", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret1_relu_ap_fixed_14_8_5_3_0_ap_ufixed_12_6_5_3_0_relu_config4_s_fu_511", "Parent" : "0",
		"CDFG" : "relu_ap_fixed_14_8_5_3_0_ap_ufixed_12_6_5_3_0_relu_config4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv8_i_i_i1668_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i1568_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i1527_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1488_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i1424_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1285_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i1240_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i1110_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i1052_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i938_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i879_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i839_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i799_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i709_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i584_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i568_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i427_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i367_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i289_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i249_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i136_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i94_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i2136_i", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret2_relu_ap_fixed_14_11_5_3_0_ap_ufixed_10_7_5_3_0_relu_config7_s_fu_540", "Parent" : "0",
		"CDFG" : "relu_ap_fixed_14_11_5_3_0_ap_ufixed_10_7_5_3_0_relu_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv5_i_i_i869_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i829_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i786_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i743_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i684_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i668_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i619_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i542_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i509_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i467_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i370_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i329_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i289_i659", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i247_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i187_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i146_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i105_i673", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i93_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i35_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i_i702", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret_relu_ap_fixed_15_11_5_3_0_ap_ufixed_11_7_5_3_0_relu_config10_s_fu_564", "Parent" : "0",
		"CDFG" : "relu_ap_fixed_15_11_5_3_0_ap_ufixed_11_7_5_3_0_relu_config10_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv5_i_i_i819_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i760_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i719_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i700_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i606_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i528_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i444_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i405_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i341_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i263_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i195_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i119_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv5_i_i_i56_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i_i1568", "Type" : "None", "Direction" : "I"}]}]}
