<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_7_4_5_3_0_16u_config3_s</name>
		<module_structure>Sequential</module_structure>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>layer3_out</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>res</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>112</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>stream_in0_input_layer</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName>FIFO_SRL</coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>13</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_3">
				<Value>
					<Obj>
						<type>0</type>
						<id>11</id>
						<name>indvar_flatten</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>37</item>
				</oprand_edges>
				<opcode>alloca</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>1</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>17</id>
						<name>indvar_flatten_write_ln0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>39</item>
					<item>40</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.42</m_delay>
				<m_topoIndex>2</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>18</id>
						<name>br_ln25</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>25</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>2</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>25</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>41</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>3</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>indvar_flatten_load</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>25</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>25</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>53</item>
					<item>203</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>4</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>21</id>
						<name>icmp_ln25</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>25</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>25</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control>auto</control>
						<opType>seteq</opType>
						<implIndex>auto</implIndex>
						<coreName>Cmp</coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>9</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>54</item>
					<item>56</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.78</m_delay>
				<m_topoIndex>5</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>add_ln25</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>25</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>25</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control>auto</control>
						<opType>add</opType>
						<implIndex>fabric</implIndex>
						<coreName>Adder</coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>57</item>
					<item>59</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.78</m_delay>
				<m_topoIndex>6</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name>br_ln25</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>25</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>25</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>60</item>
					<item>61</item>
					<item>62</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>7</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>28</id>
						<name>stream_in0_input_layer_read</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>32</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>32</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control>auto</control>
						<opType>fifo</opType>
						<implIndex>srl</implIndex>
						<coreName>FIFO_SRL</coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>80</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>43</item>
					<item>44</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>2.18</m_delay>
				<m_topoIndex>10</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>29</id>
						<name>trunc_ln32</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>32</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>32</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>4</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>45</item>
				</oprand_edges>
				<opcode>trunc</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>11</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>30</id>
						<name>_ln32</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>32</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>32</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>11</count>
					<item_version>0</item_version>
					<item>47</item>
					<item>48</item>
					<item>49</item>
					<item>63</item>
					<item>64</item>
					<item>65</item>
					<item>66</item>
					<item>67</item>
					<item>68</item>
					<item>69</item>
					<item>70</item>
				</oprand_edges>
				<opcode>call</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>12</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>31</id>
						<name>indvar_flatten_write_ln25</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>25</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>25</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>50</item>
					<item>51</item>
					<item>204</item>
					<item>205</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.42</m_delay>
				<m_topoIndex>8</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>32</id>
						<name>br_ln27</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</fileDirectory>
						<lineNumber>27</lineNumber>
						<contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_4_2_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_7_4_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_FixedHP/hls4ml_prj_VU-New</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>27</second>
									</item>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;4, 2, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;7, 4, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>52</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>13</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>34</id>
						<name>_ln0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.42</m_delay>
				<m_topoIndex>9</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>5</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_16">
				<Value>
					<Obj>
						<type>2</type>
						<id>36</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_17">
				<Value>
					<Obj>
						<type>2</type>
						<id>38</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_18">
				<Value>
					<Obj>
						<type>2</type>
						<id>46</id>
						<name>compute_output_buffer_2d_array_array_ap_ufixed_7_4_5_3_0_16u_config3_s</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<const_type>6</const_type>
				<content>&lt;constant:compute_output_buffer_2d&lt;array,array&lt;ap_ufixed&lt;7,4,5,3,0&gt;,16u&gt;,config3&gt;&gt;</content>
			</item>
			<item class_id_reference="16" object_id="_19">
				<Value>
					<Obj>
						<type>2</type>
						<id>55</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>784</content>
			</item>
			<item class_id_reference="16" object_id="_20">
				<Value>
					<Obj>
						<type>2</type>
						<id>58</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>4</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_21">
				<Obj>
					<type>3</type>
					<id>19</id>
					<name>entry</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>4294967295</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>3</count>
					<item_version>0</item_version>
					<item>11</item>
					<item>17</item>
					<item>18</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_22">
				<Obj>
					<type>3</type>
					<id>24</id>
					<name>for.body12.i.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>4294967295</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>20</item>
					<item>21</item>
					<item>22</item>
					<item>23</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_23">
				<Obj>
					<type>3</type>
					<id>33</id>
					<name>for.cond.cleanup11.i.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>4294967295</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>5</count>
					<item_version>0</item_version>
					<item>28</item>
					<item>29</item>
					<item>30</item>
					<item>31</item>
					<item>32</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_24">
				<Obj>
					<type>3</type>
					<id>35</id>
					<name>conv_2d_cl&lt;array&lt;ap_ufixed&lt;4, 2, 0, 3, 0&gt;, 1u&gt;, array&lt;ap_ufixed&lt;7, 4, 5, 3, 0&gt;, 16u&gt;, config3&gt;.exit</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>4294967295</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>34</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>35</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_25">
				<id>37</id>
				<edge_type>1</edge_type>
				<source_obj>36</source_obj>
				<sink_obj>11</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_26">
				<id>39</id>
				<edge_type>1</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>17</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_27">
				<id>40</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>17</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_28">
				<id>41</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>18</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_29">
				<id>44</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>28</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_30">
				<id>45</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>29</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_31">
				<id>47</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_32">
				<id>48</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_33">
				<id>49</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_34">
				<id>50</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_35">
				<id>51</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_36">
				<id>52</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>32</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_37">
				<id>53</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_38">
				<id>54</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_39">
				<id>56</id>
				<edge_type>1</edge_type>
				<source_obj>55</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_40">
				<id>57</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_41">
				<id>59</id>
				<edge_type>1</edge_type>
				<source_obj>58</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_42">
				<id>60</id>
				<edge_type>1</edge_type>
				<source_obj>21</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_43">
				<id>61</id>
				<edge_type>2</edge_type>
				<source_obj>33</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_44">
				<id>62</id>
				<edge_type>2</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_45">
				<id>63</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_46">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>65</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>66</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>67</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>68</id>
				<edge_type>1</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>69</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>70</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>199</id>
				<edge_type>2</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>24</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>200</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>35</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>201</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>33</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>202</id>
				<edge_type>2</edge_type>
				<source_obj>33</source_obj>
				<sink_obj>24</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>203</id>
				<edge_type>4</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>204</id>
				<edge_type>4</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>205</id>
				<edge_type>4</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_60">
			<mId>1</mId>
			<mTag>conv_2d_cl&lt;array&lt;ap_ufixed,1u&gt;,array&lt;ap_ufixed&lt;7,4,5,3,0&gt;,16u&gt;,config3&gt;</mTag>
			<mNormTag>conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_7_4_5_3_0_16u_config3_s</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>4</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>1570</mMinLatency>
			<mMaxLatency>1570</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_61">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mNormTag>Entry</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>19</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_62">
			<mId>3</mId>
			<mTag>ReadInputHeight_ReadInputWidth</mTag>
			<mNormTag>ReadInputHeight_ReadInputWidth</mNormTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>24</item>
				<item>33</item>
			</basic_blocks>
			<mII>2</mII>
			<mDepth>3</mDepth>
			<mMinTripCount>784</mMinTripCount>
			<mMaxTripCount>784</mMaxTripCount>
			<mMinLatency>1568</mMinLatency>
			<mMaxLatency>1568</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_63">
			<mId>4</mId>
			<mTag>Return</mTag>
			<mNormTag>Return</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>35</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="24" tracking_level="1" version="0" object_id="_64">
		<states class_id="25" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="26" tracking_level="1" version="0" object_id="_65">
				<id>1</id>
				<operations class_id="27" tracking_level="0" version="0">
					<count>14</count>
					<item_version>0</item_version>
					<item class_id="28" tracking_level="1" version="0" object_id="_66">
						<id>11</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_67">
						<id>12</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_68">
						<id>13</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_69">
						<id>14</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_70">
						<id>15</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_71">
						<id>16</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_72">
						<id>17</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_73">
						<id>18</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_74">
						<id>20</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_75">
						<id>21</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_76">
						<id>22</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_77">
						<id>23</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_78">
						<id>31</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_79">
						<id>34</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
				</operations>
			</item>
			<item class_id_reference="26" object_id="_80">
				<id>2</id>
				<operations>
					<count>3</count>
					<item_version>0</item_version>
					<item class_id_reference="28" object_id="_81">
						<id>28</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_82">
						<id>29</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_83">
						<id>30</id>
						<stage>2</stage>
						<latency>2</latency>
					</item>
				</operations>
			</item>
			<item class_id_reference="26" object_id="_84">
				<id>3</id>
				<operations>
					<count>5</count>
					<item_version>0</item_version>
					<item class_id_reference="28" object_id="_85">
						<id>25</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_86">
						<id>26</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_87">
						<id>27</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_88">
						<id>30</id>
						<stage>1</stage>
						<latency>2</latency>
					</item>
					<item class_id_reference="28" object_id="_89">
						<id>32</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
				</operations>
			</item>
		</states>
		<transitions class_id="29" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="30" tracking_level="1" version="0" object_id="_90">
				<inState>2</inState>
				<outState>3</outState>
				<condition class_id="31" tracking_level="0" version="0">
					<id>-1</id>
					<sop class_id="32" tracking_level="0" version="0">
						<count>1</count>
						<item_version>0</item_version>
						<item class_id="33" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</item>
					</sop>
				</condition>
			</item>
			<item class_id_reference="30" object_id="_91">
				<inState>1</inState>
				<outState>2</outState>
				<condition>
					<id>-1</id>
					<sop>
						<count>1</count>
						<item_version>0</item_version>
						<item>
							<count>0</count>
							<item_version>0</item_version>
						</item>
					</sop>
				</condition>
			</item>
		</transitions>
	</fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="35" tracking_level="0" version="0">
		<count>13</count>
		<item_version>0</item_version>
		<item class_id="36" tracking_level="0" version="0">
			<first>11</first>
			<second class_id="37" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>17</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>18</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>21</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>29</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>31</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>32</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>34</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="38" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="39" tracking_level="0" version="0">
			<first>19</first>
			<second class_id="40" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>33</first>
			<second>
				<first>1</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>35</first>
			<second>
				<first>2</first>
				<second>2</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="41" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="42" tracking_level="1" version="0" object_id="_92">
			<region_name>ReadInputHeight_ReadInputWidth</region_name>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>24</item>
				<item>33</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>2</interval>
			<pipe_depth>3</pipe_depth>
			<mDBIIViolationVec class_id="43" tracking_level="0" version="0">
				<count>0</count>
				<item_version>0</item_version>
			</mDBIIViolationVec>
		</item>
	</regions>
	<dp_fu_nodes class_id="44" tracking_level="0" version="0">
		<count>9</count>
		<item_version>0</item_version>
		<item class_id="45" tracking_level="0" version="0">
			<first>52</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>11</item>
			</second>
		</item>
		<item>
			<first>56</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>28</item>
			</second>
		</item>
		<item>
			<first>62</first>
			<second>
				<count>2</count>
				<item_version>0</item_version>
				<item>30</item>
				<item>30</item>
			</second>
		</item>
		<item>
			<first>85</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>17</item>
			</second>
		</item>
		<item>
			<first>90</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>20</item>
			</second>
		</item>
		<item>
			<first>93</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>21</item>
			</second>
		</item>
		<item>
			<first>99</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>22</item>
			</second>
		</item>
		<item>
			<first>105</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>31</item>
			</second>
		</item>
		<item>
			<first>110</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>29</item>
			</second>
		</item>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="47" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="48" tracking_level="0" version="0">
			<first>add_ln25_fu_99</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>22</item>
			</second>
		</item>
		<item>
			<first>icmp_ln25_fu_93</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>21</item>
			</second>
		</item>
		<item>
			<first>indvar_flatten_fu_52</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>11</item>
			</second>
		</item>
		<item>
			<first>trunc_ln32_fu_110</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>29</item>
			</second>
		</item>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>1</count>
		<item_version>0</item_version>
		<item>
			<first>grp_compute_output_buffer_2d_array_array_ap_ufixed_7_4_5_3_0_16u_config3_s_fu_62</first>
			<second>
				<count>2</count>
				<item_version>0</item_version>
				<item>30</item>
				<item>30</item>
			</second>
		</item>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>4</count>
		<item_version>0</item_version>
		<item>
			<first>indvar_flatten_load_load_fu_90</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>20</item>
			</second>
		</item>
		<item>
			<first>store_ln0_store_fu_85</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>17</item>
			</second>
		</item>
		<item>
			<first>store_ln25_store_fu_105</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>31</item>
			</second>
		</item>
		<item>
			<first>stream_in0_input_layer_read_read_fu_56</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>28</item>
			</second>
		</item>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="49" tracking_level="0" version="0">
		<count>2</count>
		<item_version>0</item_version>
		<item class_id="50" tracking_level="0" version="0">
			<first class_id="51" tracking_level="0" version="0">
				<first>void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer</first>
				<second>100</second>
			</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>30</item>
			</second>
		</item>
		<item>
			<first>
				<first>void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1</first>
				<second>100</second>
			</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>30</item>
			</second>
		</item>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>2</count>
		<item_version>0</item_version>
		<item>
			<first>115</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>11</item>
			</second>
		</item>
		<item>
			<first>122</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>21</item>
			</second>
		</item>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>2</count>
		<item_version>0</item_version>
		<item>
			<first>icmp_ln25_reg_122</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>21</item>
			</second>
		</item>
		<item>
			<first>indvar_flatten_reg_115</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>11</item>
			</second>
		</item>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="52" tracking_level="0" version="0">
		<count>2</count>
		<item_version>0</item_version>
		<item class_id="53" tracking_level="0" version="0">
			<first>layer3_out</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>
					<first>call</first>
					<second>
						<count>1</count>
						<item_version>0</item_version>
						<item>30</item>
					</second>
				</item>
			</second>
		</item>
		<item>
			<first>stream_in0_input_layer</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>
					<first>read</first>
					<second>
						<count>1</count>
						<item_version>0</item_version>
						<item>28</item>
					</second>
				</item>
			</second>
		</item>
	</dp_port_io_nodes>
	<port2core>
		<count>1</count>
		<item_version>0</item_version>
		<item>
			<first>2</first>
			<second>
				<first>666</first>
				<second>10</second>
			</second>
		</item>
	</port2core>
	<node2core>
		<count>4</count>
		<item_version>0</item_version>
		<item>
			<first>21</first>
			<second>
				<first>526</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>8</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>666</first>
				<second>10</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>-1</first>
				<second>-1</second>
			</second>
		</item>
	</node2core>
	<sched_res class_id="54" tracking_level="1" version="0" object_id="_93">
		<ResourceTableActual class_id="55" tracking_level="0" version="0">
			<II>2</II>
		</ResourceTableActual>
		<ResourceTableFailed class_id="56" tracking_level="0" version="0">
			<II>-1</II>
		</ResourceTableFailed>
	</sched_res>
</syndb>
</boost_serialization>

