[hls]
relative_roots=/work/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7573_ebops=11698_VU_DA_bitfile/vitis_workspace/myproject
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=store_result<float, nnet::array<ap_fixed<17, 8, (ap_q_mode)5, (ap_o_mode)3, 0>, 3u> >/VITIS_LOOP_29_1 
syn.directive.pipeline=load_input<float, nnet::array<ap_fixed<11, 7, (ap_q_mode)0, (ap_o_mode)3, 0>, 60u> >/VITIS_LOOP_13_1 


