# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline store_result/store_result_loop
set_directive_pipeline load_input/VITIS_LOOP_8_1
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten load_input/load_input_loop
