[hls]
relative_roots=/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_hgq2/Training_AdaptiveHP/hls4ml_prj_VU_fifo-opt/vitis_workspace/myproject
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=store_result<float, nnet::array<ap_fixed<15, 9, (ap_q_mode)5, (ap_o_mode)3, 0>, 10u> >/VITIS_LOOP_29_1 
syn.directive.pipeline=load_input<float, nnet::array<ap_ufixed<4, 2, (ap_q_mode)0, (ap_o_mode)3, 0>, 1u> >/VITIS_LOOP_14_2 


