Backend: VitisUnified
ClockPeriod: '5'
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    conv0:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 1
      Trace: false
    conv0_iq:
      Precision:
        result: auto
      Trace: false
    conv0_relu:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 1
      Trace: false
    conv1_iq:
      Precision:
        result: auto
      Trace: false
    conv1_relu:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    dense0:
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 1
      Trace: false
    dense0_iq:
      Precision:
        result: auto
      Trace: false
    flatten:
      Precision:
        result: auto
      Trace: false
    input_image:
      Precision:
        result: auto
      Trace: false
    pool0:
      ConvImplementation: LineBuffer
      Precision:
        accum: auto
        result: auto
      ReuseFactor: 1
      Trace: false
    pool1:
      ConvImplementation: LineBuffer
      Precision:
        accum: auto
        result: auto
      ReuseFactor: 1
      Trace: false
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
InputShapes:
  input_image:
  - 28
  - 28
  - 1
KerasModel: !keras_model '/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_expo_hgq2/Training_AdaptiveHP/hls4ml_prj_VU_EXPO/keras_model.keras'
OutputDir: /home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/MNIST_expo_hgq2/Training_AdaptiveHP/hls4ml_prj_VU_EXPO
OutputPredictions: null
OutputShapes:
  layer12_out:
  - 10
Part: xck26-sfvc784-2LV-c
ProjectName: myproject
Stamp: 7e6f4abb
Version: 1.0.0
VitisUnifiedConfig:
  Board: kv260
  Driver: python
  InputDtype: float
  OutputDtype: float
  axi_mode: axi_master
  in_stream_buf_size: 128
  out_stream_buf_size: 128
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
