

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "40", "80", "88", "89", "90", "91", "92", "93", "94"],
		"CDFG" : "myproject_axi_master",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "entry_proc_U0"},
			{"ID" : "5", "Name" : "load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0"}],
		"OutputProcess" : [
			{"ID" : "80", "Name" : "store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0"}],
		"Port" : [
			{"Name" : "gmem_in0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0", "Port" : "gmem_in0"}]},
			{"Name" : "gmem_out0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "80", "SubInstance" : "store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0", "Port" : "gmem_out0"}]},
			{"Name" : "gmem_in0_ptr_input_layer", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out0_ptr_layer12_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "batch_size", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0", "Port" : "stream_in0_input_layer"},
					{"ID" : "40", "SubInstance" : "compute_U0", "Port" : "stream_in0_input_layer"}]},
			{"Name" : "stream_out0_layer12_out", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "compute_U0", "Port" : "stream_out0_layer12_out"},
					{"ID" : "80", "SubInstance" : "store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0", "Port" : "stream_out0_layer12_out"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_in0_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out0_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_out0_ptr_layer12_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out0_ptr_layer12_out_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["80"], "DependentChan" : "88", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "gmem_out0_ptr_layer12_out_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0", "Parent" : "0", "Child" : ["6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39"],
		"CDFG" : "load_input_float_array_ap_fixed_11_5_0_3_0_16u_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_in0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_in0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "batch_size", "Type" : "None", "Direction" : "I"},
			{"Name" : "batch_size_c1", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["40"], "DependentChan" : "89", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_c1_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["40"], "DependentChan" : "90", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "stream_in0_input_layer_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_13_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "16", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage12", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage12_subdone", "QuitState" : "ap_ST_fsm_pp0_stage12", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage12_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.fpext_32ns_64_2_no_dsp_1_U3", "Parent" : "5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U4", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U5", "Parent" : "5"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U6", "Parent" : "5"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U7", "Parent" : "5"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U8", "Parent" : "5"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U9", "Parent" : "5"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U10", "Parent" : "5"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U11", "Parent" : "5"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U12", "Parent" : "5"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U13", "Parent" : "5"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U14", "Parent" : "5"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U15", "Parent" : "5"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U16", "Parent" : "5"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U17", "Parent" : "5"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U18", "Parent" : "5"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U19", "Parent" : "5"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U20", "Parent" : "5"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U21", "Parent" : "5"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U22", "Parent" : "5"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U23", "Parent" : "5"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U24", "Parent" : "5"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U25", "Parent" : "5"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U26", "Parent" : "5"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U27", "Parent" : "5"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U28", "Parent" : "5"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U29", "Parent" : "5"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U30", "Parent" : "5"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U31", "Parent" : "5"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U32", "Parent" : "5"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U33", "Parent" : "5"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.bitselect_1ns_54ns_6ns_1_1_1_U34", "Parent" : "5"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.sparsemux_9_3_11_1_1_U35", "Parent" : "5"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_float_array_ap_fixed_11_5_0_3_0_16u_U0.flow_control_loop_pipe_U", "Parent" : "5"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0", "Parent" : "0", "Child" : ["41"],
		"CDFG" : "compute",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "5",
		"StartFifo" : "start_for_compute_U0_U",
		"Port" : [
			{"Name" : "batch_size", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "89", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "batch_size_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["80"], "DependentChan" : "91", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "90", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_myproject_fu_62", "Port" : "stream_in0_input_layer", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "stream_out0_layer12_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["80"], "DependentChan" : "92", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_myproject_fu_62", "Port" : "stream_out0_layer12_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_42_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62", "Parent" : "40", "Child" : ["42", "54", "55", "57", "58", "61", "62", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79"],
		"CDFG" : "myproject",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "20", "EstimateLatencyMax" : "20",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "42", "Name" : "dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0"}],
		"OutputProcess" : [
			{"ID" : "62", "Name" : "dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0"}],
		"Port" : [
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0", "Port" : "stream_in0_input_layer"}]},
			{"Name" : "stream_out0_layer12_out", "Type" : "Fifo", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0", "Port" : "stream_out0_layer12_out"}]}]},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0", "Parent" : "41", "Child" : ["43"],
		"CDFG" : "dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "layer3_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["54"], "DependentChan" : "68", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_in0_input_layer", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "stream_in0_input_layer_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "43", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75", "Parent" : "42", "Child" : ["44", "45", "46", "47", "48", "49", "50", "51", "52", "53"],
		"CDFG" : "dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "44", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_9s_20_1_1_U44", "Parent" : "43"},
	{"ID" : "45", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_9ns_20_1_1_U45", "Parent" : "43"},
	{"ID" : "46", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_7s_18_1_1_U46", "Parent" : "43"},
	{"ID" : "47", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_10s_21_1_1_U47", "Parent" : "43"},
	{"ID" : "48", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_9ns_19_1_1_U48", "Parent" : "43"},
	{"ID" : "49", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_10ns_20_1_1_U49", "Parent" : "43"},
	{"ID" : "50", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_8s_19_1_1_U50", "Parent" : "43"},
	{"ID" : "51", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_10ns_21_1_1_U51", "Parent" : "43"},
	{"ID" : "52", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_8s_18_1_1_U52", "Parent" : "43"},
	{"ID" : "53", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_fixed_16u_array_ap_fixed_14_9_5_3_0_64u_config3_U0.grp_dense_latency_ap_fixed_11_5_0_3_0_ap_fixed_14_9_5_3_0_config3_s_fu_75.mul_11s_10s_20_1_1_U53", "Parent" : "43"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_64u_array_ap_ufixed_10_6_0_3_0_64u_relu_config4_U0", "Parent" : "41",
		"CDFG" : "relu_array_ap_fixed_64u_array_ap_ufixed_10_6_0_3_0_64u_relu_config4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "42",
		"StartFifo" : "start_for_relu_array_ap_fixed_64u_array_ap_ufixed_10_6_0_3_0_64u_relu_config4bkb_U",
		"Port" : [
			{"Name" : "layer3_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["42"], "DependentChan" : "68", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer4_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["55"], "DependentChan" : "69", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer4_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_64u_array_ap_fixed_16_13_5_3_0_32u_config6_U0", "Parent" : "41", "Child" : ["56"],
		"CDFG" : "dense_array_ap_ufixed_64u_array_ap_fixed_16_13_5_3_0_32u_config6_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "54",
		"StartFifo" : "start_for_dense_array_ap_ufixed_64u_array_ap_fixed_16_13_5_3_0_32u_config6_U0_U",
		"Port" : [
			{"Name" : "layer4_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["54"], "DependentChan" : "69", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer6_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["57"], "DependentChan" : "70", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer6_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "56", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_64u_array_ap_fixed_16_13_5_3_0_32u_config6_U0.grp_dense_latency_ap_ufixed_10_6_0_3_0_ap_fixed_16_13_5_3_0_config6_s_fu_229", "Parent" : "55",
		"CDFG" : "dense_latency_ap_ufixed_10_6_0_3_0_ap_fixed_16_13_5_3_0_config6_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_32_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_33_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_34_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_35_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_37_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_40_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_41_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_42_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_43_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_44_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_45_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_49_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_51_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_52_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_53_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_54_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_55_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_56_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_57_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_58_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_59_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_60_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_62_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config7_U0", "Parent" : "41",
		"CDFG" : "relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "55",
		"StartFifo" : "start_for_relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config7_U0_U",
		"Port" : [
			{"Name" : "layer6_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["55"], "DependentChan" : "70", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer6_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer7_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["58"], "DependentChan" : "71", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer7_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_14_11_5_3_0_32u_config9_U0", "Parent" : "41", "Child" : ["59"],
		"CDFG" : "dense_array_ap_ufixed_32u_array_ap_fixed_14_11_5_3_0_32u_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "57",
		"StartFifo" : "start_for_dense_array_ap_ufixed_32u_array_ap_fixed_14_11_5_3_0_32u_config9_U0_U",
		"Port" : [
			{"Name" : "layer7_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["57"], "DependentChan" : "71", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer7_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer9_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["61"], "DependentChan" : "72", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer9_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "59", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_14_11_5_3_0_32u_config9_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_14_11_5_3_0_config9_s_fu_147", "Parent" : "58", "Child" : ["60"],
		"CDFG" : "dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_14_11_5_3_0_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "60", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_14_11_5_3_0_32u_config9_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_14_11_5_3_0_config9_s_fu_147.mul_8ns_8ns_15_1_1_U136", "Parent" : "59"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10_U0", "Parent" : "41",
		"CDFG" : "relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "58",
		"StartFifo" : "start_for_relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10cud_U",
		"Port" : [
			{"Name" : "layer9_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["58"], "DependentChan" : "72", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer9_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer10_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["62"], "DependentChan" : "73", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer10_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0", "Parent" : "41", "Child" : ["63"],
		"CDFG" : "dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "61",
		"StartFifo" : "start_for_dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0_U",
		"Port" : [
			{"Name" : "layer10_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["61"], "DependentChan" : "73", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer10_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_out0_layer12_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "stream_out0_layer12_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "63", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_18_8_5_3_0_config12_s_fu_119", "Parent" : "62", "Child" : ["64", "65", "66", "67"],
		"CDFG" : "dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_18_8_5_3_0_config12_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "64", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_18_8_5_3_0_config12_s_fu_119.mul_8ns_8ns_15_1_1_U169", "Parent" : "63"},
	{"ID" : "65", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_18_8_5_3_0_config12_s_fu_119.mul_8ns_7s_15_1_1_U170", "Parent" : "63"},
	{"ID" : "66", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_18_8_5_3_0_config12_s_fu_119.mul_8ns_7ns_14_1_1_U171", "Parent" : "63"},
	{"ID" : "67", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0.grp_dense_latency_ap_ufixed_8_6_0_3_0_ap_fixed_18_8_5_3_0_config12_s_fu_119.mul_8ns_8ns_15_1_1_U172", "Parent" : "63"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer3_out_U", "Parent" : "41"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer4_out_U", "Parent" : "41"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer6_out_U", "Parent" : "41"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer7_out_U", "Parent" : "41"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer9_out_U", "Parent" : "41"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.layer10_out_U", "Parent" : "41"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_64u_array_ap_ufixed_10_6_0_3_0_64u_relu_config4bkb_U", "Parent" : "41"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_64u_array_ap_fixed_16_13_5_3_0_32u_config6_U0_U", "Parent" : "41"},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config7_U0_U", "Parent" : "41"},
	{"ID" : "77", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_32u_array_ap_fixed_14_11_5_3_0_32u_config9_U0_U", "Parent" : "41"},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_relu_array_ap_fixed_32u_array_ap_ufixed_8_6_0_3_0_32u_relu_config10cud_U", "Parent" : "41"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_myproject_fu_62.start_for_dense_array_ap_ufixed_32u_array_ap_fixed_18_8_5_3_0_5u_config12_U0_U", "Parent" : "41"},
	{"ID" : "80", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0", "Parent" : "0", "Child" : ["81"],
		"CDFG" : "store_result_float_array_ap_fixed_18_8_5_3_0_5u_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "4",
		"StartFifo" : "start_for_store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0_U",
		"Port" : [
			{"Name" : "gmem_out0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out0_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_out0_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "81", "SubInstance" : "grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81", "Port" : "gmem_out0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["4"], "DependentChan" : "88", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "batch_size", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["40"], "DependentChan" : "91", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "batch_size_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "stream_out0_layer12_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["40"], "DependentChan" : "92", "DependentChanDepth" : "128", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "81", "SubInstance" : "grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81", "Port" : "stream_out0_layer12_out", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81", "Parent" : "80", "Child" : ["82", "83", "84", "85", "86", "87"],
		"CDFG" : "store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "batch_size_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out0_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln29", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_out0_layer12_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "stream_out0_layer12_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_29_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_18_18_1_1_U215", "Parent" : "81"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_18_18_1_1_U216", "Parent" : "81"},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_18_18_1_1_U217", "Parent" : "81"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_18_18_1_1_U218", "Parent" : "81"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81.ctlz_18_18_1_1_U219", "Parent" : "81"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0.grp_store_result_float_array_ap_fixed_5u_Pipeline_VITIS_LOOP_29_1_fu_81.flow_control_loop_pipe_sequential_init_U", "Parent" : "81"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out0_ptr_layer12_out_c_U", "Parent" : "0"},
	{"ID" : "89", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.batch_size_c1_U", "Parent" : "0"},
	{"ID" : "90", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.stream_in0_input_layer_U", "Parent" : "0"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.batch_size_c_U", "Parent" : "0"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.stream_out0_layer12_out_U", "Parent" : "0"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_store_result_float_array_ap_fixed_18_8_5_3_0_5u_U0_U", "Parent" : "0"},
	{"ID" : "94", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_U0_U", "Parent" : "0"}]}
