

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "7", "8", "9", "10", "13", "14"],
		"CDFG" : "hgq2_1_hls4ml_prj_Vitis_latency_reusefactor1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "9", "EstimateLatencyMin" : "9", "EstimateLatencyMax" : "9",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_layer", "Type" : "Vld", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "input_layer_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer13_out_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "layer13_out_4", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s_fu_303", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6"],
		"CDFG" : "dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "1",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv8_i_i_i581_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i540_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i501_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i463_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i429_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i390_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i351_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i313_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i274_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i198_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i159_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i48_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i_i", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s_fu_303.mul_11s_9ns_20_1_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s_fu_303.mul_12s_9ns_21_1_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s_fu_303.mul_12s_9ns_21_1_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s_fu_303.mul_12s_10s_21_1_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_fixed_26_19_5_3_0_ap_fixed_14_8_5_3_0_config3_s_fu_303.mul_11s_9s_20_1_1_U5", "Parent" : "1"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret2_relu_ap_fixed_14_8_5_3_0_ap_ufixed_12_6_5_3_0_relu_config4_s_fu_320", "Parent" : "0",
		"CDFG" : "relu_ap_fixed_14_8_5_3_0_ap_ufixed_12_6_5_3_0_relu_config4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "layer3_out_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_31_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_32_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_34_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_38_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_39_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_44_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_45_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_47_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_50_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_51_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_56_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_57_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer3_out_62_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_ufixed_11_6_5_3_0_ap_fixed_14_11_5_3_0_config6_s_fu_349", "Parent" : "0",
		"CDFG" : "dense_latency_ap_ufixed_11_6_5_3_0_ap_fixed_14_11_5_3_0_config6_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "1",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv8_i_i_i1458_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1375_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i1333_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1297_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1246_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1177_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1122_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i1081_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i972_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i919_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i824_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i771_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i734_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i693_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i639_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i563_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i524_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i429_i142", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i388_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i336_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i275_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i242_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i147_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i108_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i_i185", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret4_relu_ap_fixed_14_11_5_3_0_ap_ufixed_10_7_5_3_0_relu_config7_s_fu_378", "Parent" : "0",
		"CDFG" : "relu_ap_fixed_14_11_5_3_0_ap_ufixed_10_7_5_3_0_relu_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "layer6_out_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_20_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer6_out_30_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_ufixed_9_7_5_3_0_ap_fixed_15_11_5_3_0_config9_s_fu_402", "Parent" : "0", "Child" : ["11", "12"],
		"CDFG" : "dense_latency_ap_ufixed_9_7_5_3_0_ap_fixed_15_11_5_3_0_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "1",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv_i_i_i887_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i850_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i816_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i776_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i728_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i687_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i618_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i551_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i496_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv4_i_i_i_i476_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i379_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i345_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv4_i_i_i_i326_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i271_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i216_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i184_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i143_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i104_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i_i_i53_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv8_i_i_i_i499", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_ufixed_9_7_5_3_0_ap_fixed_15_11_5_3_0_config9_s_fu_402.mul_9ns_7ns_15_1_1_U93", "Parent" : "10"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_ufixed_9_7_5_3_0_ap_fixed_15_11_5_3_0_config9_s_fu_402.mul_7ns_6ns_12_1_1_U94", "Parent" : "10"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret_relu_ap_fixed_15_11_5_3_0_ap_ufixed_11_7_5_3_0_relu_config10_s_fu_426", "Parent" : "0",
		"CDFG" : "relu_ap_fixed_15_11_5_3_0_ap_ufixed_11_7_5_3_0_relu_config10_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "layer9_out_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer9_out_31_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dense_latency_ap_ufixed_10_7_5_3_0_ap_fixed_10_7_5_3_0_config12_s_fu_445", "Parent" : "0",
		"CDFG" : "dense_latency_ap_ufixed_10_7_5_3_0_ap_fixed_10_7_5_3_0_config12_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "1",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"}]}]}
