services:
    hls4ml-kv260-testbench:
        container_name: hls4ml-kv260-testbench
        image: 'hls4ml-kv260-testbench:final'
        volumes:
            - './environments/:/work/environments/'
            - '~/Bachelor/HLS4ML_testbench_KV260/development/:/work/development/'
        ports:
            - '8443:8443'
        init: true # Needed for proper handling of Vivado-processes during synthesis
