# syntax=docker/dockerfile:1

# Credit for inspiration goes to 
# FastMachineLearning (https://github.com/fastmachinelearning/hls4ml-tutorial/blob/docker_build/docker/)
# ESnet (https://github.com/esnet/xilinx-tools-docker/blob/main/Dockerfile)
# filmil (https://github.com/filmil/vivado-docker/blob/main/docker/Dockerfile)
# cmu-sei (https://github.com/cmu-sei/hls4ml-docker/blob/main/Dockerfile)

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

ENV TOOL_VERSION=2025.2
ARG TARGET_INSTALL_DIR=/opt/Xilinx
ARG HOST_INSTALLER_ARCHIVE="./installer/FPGAs_AdaptiveSoCs_Unified_SDI_${TOOL_VERSION}_1114_2157_1.tar"
ARG HOST_INSTALLER_CONFIG="./installer/install_config.txt"
ARG TOOL_INSTALLER_ARCHIVE="/tmp/installer/archive.tar"
ARG TOOL_INSTALLER_CONFIG="/tmp/installer/install_config.txt"

# Install dependencies and cache
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \ 
    && apt-get update &&  apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
    # Packages required for running the installer and Vitis
      ca-certificates \
      libtinfo5 \
      locales \
      lsb-release \
      net-tools \
      patch \
      unzip \
      wget \
    # From installLibs.sh:
      ### AIE Tools prerequisite libraries
      libc6-dev-i386 net-tools \
      graphviz \
      make \
      ### Vitis Tools prerequisite libraries
      #unzip \
      zip \
      # https://adaptivesupport.amd.com/s/article/76616?language=en_US
      libtinfo5 \
      g++ \
      xvfb \
      #git \
      #libncurses5 \
      libncurses5-dev \
      libc6-dev-i386 \
      libnss3-dev \
      libgdk-pixbuf2.0-dev \
      libgtk-3-dev \
      libxss-dev  \
      libasound2   \
      #compat-openssl10  \
      openssl \
      fdisk  \
      libsecret-1-dev \
    # Custom environment
      python3 \
      python3-pip \
      git \
    && apt-get autoclean \
    && apt-get autoremove \
  # && Vivado needs locale EN_us
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*


  
# Bind mounts the ./installer-directory under building so they are not redundantly 
# copied into the containers filesystem from the build context.
# The unarchive-process is split from installation to speed up cancelled builds
RUN --mount=type=bind,source=${HOST_INSTALLER_ARCHIVE},target=${TOOL_INSTALLER_ARCHIVE} \
    echo "Extracting archive (this takes a while)..." \
    && mkdir -p /tmp/installer-extract \
    && tar -xf ${TOOL_INSTALLER_ARCHIVE} -C /tmp/installer-extract 

# Import config file for installation
COPY $HOST_INSTALLER_CONFIG $TOOL_INSTALLER_CONFIG

# Install Vitis and Vivado. 
RUN echo "Running xsetup batch install..." \
    && cd "/tmp/installer-extract/$(ls /tmp/installer-extract)" \
    && ./xsetup \
      --batch Install \
      --location ${TARGET_INSTALL_DIR} \
      --config ${TOOL_INSTALLER_CONFIG} \
      --agree XilinxEULA,3rdPartyEULA \
    && echo "Cleaning up extracted archive..." \
    && rm -rf /tmp/installer*

# Check dependencies missing for running Vivado and Vitis
# This' the official method, however, we extracted the packages and installed them initially
#RUN bash ${TARGET_INSTALL_DIR}/${TOOL_VERSION}/Vitis/scripts/installLibs.sh && \
#	bash ${TARGET_INSTALL_DIR}/${TOOL_VERSION}/Vivado/scripts/installLibs.sh


# Setting up HLS4ML and custom environment
#USER 

# Entrypoint sources the Vivado/Vitis files
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

# Jupyter notebook
#WORKDIR /work
#CMD ["jupyter", "notebook", ""]
EXPOSE 8888

CMD ["/bin/bash", "-l"]