# syntax=docker/dockerfile:1
FROM ubuntu:22.04

#WORKDIR /

RUN apt-get -y update && apt-get install -y --no-install-recommends python3

# Vivado needs locale EN_us
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

 # Jupyter notebook
EXPOSE 8888