[hls]
relative_roots=/work/development/_OldExports/testmodel/2/hls4ml_prj_VitisUnifiedKV260_2025.2_axi_stream/vitis_workspace/myproject
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=store_result/store_result_loop 
syn.directive.pipeline=load_input/load_input_loop 


