Backend: VitisUnified
ClockPeriod: 5ns
ClockUncertainty: 12.5%
HLSConfig:
  Model:
    BitExact: null
    Precision: fixed<16,6>
    ReuseFactor: 1
IOType: io_stream
InputData: null
InputShapes:
  linput:
  - 16
KerasModel: !keras_model '/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/hls4ml-dev-testenv/testmodel/2/hls4ml_prj_VitisUnifiedKV260_1/keras_model.keras'
OutputDir: /home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/hls4ml-dev-testenv/testmodel/2/hls4ml_prj_VitisUnifiedKV260_1
OutputPredictions: null
OutputShapes:
  layer5_out:
  - 5
Part: xck26-sfvc784-2LV-c
ProjectName: myproject
Stamp: 4c09774a
Version: 1.0.0
VitisUnifiedConfig:
  Board: kv260
  Driver: python
  InputDtype: float
  OutputDtype: float
  axi_mode: axi_master
  in_stream_buf_size: 128
  out_stream_buf_size: 128
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
