Backend: Vitis
ClockPeriod: '5'
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    Precision: fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 60
KerasModel: !keras_model '/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_DA_bitfile/keras_model.keras'
OutputDir: /home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/pixsplit/pixsplit_hgq2/Training_AdaptiveHP/hls4ml_prj_acc=0.7084_ebops=864_VU_DA_bitfile
OutputPredictions: null
OutputShapes:
  layer15_out:
  - 3
Part: xck26-sfvc784-2LV-c
ProjectName: myproject
Stamp: 75dd8a67
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
