Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    Precision: auto
    ReuseFactor: 1
    Strategy: distributed_arithmetic
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 16
KerasModel: !keras_model '/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/hgq2/1/hls4ml_prj_Vitis_da4ml/keras_model.keras'
OutputDir: /home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/hgq2/1/hls4ml_prj_Vitis_da4ml
OutputPredictions: null
OutputShapes:
  layer13_out:
  - 5
Part: xck26-sfvc784-2LV-c
ProjectName: hgq2_1_hls4ml_prj_Vitis_da4ml
Stamp: 35953c5c
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
