[hls]
relative_roots=/work/development/jettag/jettag-hgq2/Training_FixedHP/hls4ml_prj_acc=0.7590_ebops=11634_VU_DA_bitfile/vitis_workspace/myproject
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=store_result<float, nnet::array<ap_fixed<17, 8, (ap_q_mode)5, (ap_o_mode)3, 0>, 5u> >/VITIS_LOOP_29_1 
syn.directive.pipeline=load_input<float, nnet::array<ap_fixed<11, 5, (ap_q_mode)0, (ap_o_mode)3, 0>, 16u> >/VITIS_LOOP_13_1 


