[hls]
relative_roots=/work/development/jettag/jet_baseline/the_baseline/hls4ml_prj_acc=0.7685_VU_DA_bitfile/vitis_workspace/myproject
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=store_result<float, nnet::array<ap_fixed<16, 6, (ap_q_mode)5, (ap_o_mode)3, 0>, 5u> >/VITIS_LOOP_29_1 
syn.directive.pipeline=nnet::init_exp_table<ap_ufixed<37, 17, (ap_q_mode)5, (ap_o_mode)3, 0>, softmax_config9>/VITIS_LOOP_151_1 
syn.directive.pipeline=load_input<float, nnet::array<ap_fixed<16, 6, (ap_q_mode)5, (ap_o_mode)3, 0>, 16u> >/VITIS_LOOP_13_1 


