-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (lin64) Build 6299465 Fri Nov 14 12:34:56 MST 2025
-- Date        : Thu May  7 15:56:05 2026
-- Host        : 11c2efc5f272 running 64-bit Ubuntu 22.04.5 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vitis_design_myproject_axi_master_1_0_stub.vhdl
-- Design      : vitis_design_myproject_axi_master_1_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xck26-sfvc784-2LV-c
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem_in0_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_in0_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_in0_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_in0_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_in0_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_in0_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_in0_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_ARREADY : in STD_LOGIC;
    m_axi_gmem_in0_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_in0_ARVALID : out STD_LOGIC;
    m_axi_gmem_in0_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_in0_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_in0_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_in0_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_in0_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_in0_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_in0_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_AWREADY : in STD_LOGIC;
    m_axi_gmem_in0_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_in0_AWVALID : out STD_LOGIC;
    m_axi_gmem_in0_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_in0_BREADY : out STD_LOGIC;
    m_axi_gmem_in0_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_in0_BVALID : in STD_LOGIC;
    m_axi_gmem_in0_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_in0_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_in0_RLAST : in STD_LOGIC;
    m_axi_gmem_in0_RREADY : out STD_LOGIC;
    m_axi_gmem_in0_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_in0_RVALID : in STD_LOGIC;
    m_axi_gmem_in0_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_in0_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_in0_WLAST : out STD_LOGIC;
    m_axi_gmem_in0_WREADY : in STD_LOGIC;
    m_axi_gmem_in0_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_in0_WVALID : out STD_LOGIC;
    m_axi_gmem_out0_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_out0_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_out0_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_out0_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_out0_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_out0_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_out0_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_ARREADY : in STD_LOGIC;
    m_axi_gmem_out0_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_out0_ARVALID : out STD_LOGIC;
    m_axi_gmem_out0_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_out0_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_out0_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_out0_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_out0_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_out0_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_out0_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_AWREADY : in STD_LOGIC;
    m_axi_gmem_out0_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_out0_AWVALID : out STD_LOGIC;
    m_axi_gmem_out0_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_out0_BREADY : out STD_LOGIC;
    m_axi_gmem_out0_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_out0_BVALID : in STD_LOGIC;
    m_axi_gmem_out0_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_out0_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_out0_RLAST : in STD_LOGIC;
    m_axi_gmem_out0_RREADY : out STD_LOGIC;
    m_axi_gmem_out0_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_out0_RVALID : in STD_LOGIC;
    m_axi_gmem_out0_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_out0_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_out0_WLAST : out STD_LOGIC;
    m_axi_gmem_out0_WREADY : in STD_LOGIC;
    m_axi_gmem_out0_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_out0_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "vitis_design_myproject_axi_master_1_0,myproject_axi_master,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "vitis_design_myproject_axi_master_1_0,myproject_axi_master,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=myproject_axi_master,x_ipVersion=1.0,x_ipCoreRevision=0,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_GMEM_IN0_ID_WIDTH=1,C_M_AXI_GMEM_IN0_ADDR_WIDTH=64,C_M_AXI_GMEM_IN0_DATA_WIDTH=32,C_M_AXI_GMEM_IN0_AWUSER_WIDTH=1,C_M_AXI_GMEM_IN0_ARUSER_WIDTH=1,C_M_AXI_GMEM_IN0_WUSER_WIDTH=1,C_M_AXI_GMEM_IN0_RUSER_WIDTH=1,C_M_AXI_GMEM_IN0_BUSER_WIDTH=1,C_M_AXI_GMEM_IN0_USER_VALUE=0x00000000,C_M_AXI_GMEM_IN0_PROT_VALUE=000,C_M_AXI_GMEM_IN0_CACHE_VALUE=0011,C_M_AXI_GMEM_OUT0_ID_WIDTH=1,C_M_AXI_GMEM_OUT0_ADDR_WIDTH=64,C_M_AXI_GMEM_OUT0_DATA_WIDTH=32,C_M_AXI_GMEM_OUT0_AWUSER_WIDTH=1,C_M_AXI_GMEM_OUT0_ARUSER_WIDTH=1,C_M_AXI_GMEM_OUT0_WUSER_WIDTH=1,C_M_AXI_GMEM_OUT0_RUSER_WIDTH=1,C_M_AXI_GMEM_OUT0_BUSER_WIDTH=1,C_M_AXI_GMEM_OUT0_USER_VALUE=0x00000000,C_M_AXI_GMEM_OUT0_PROT_VALUE=000,C_M_AXI_GMEM_OUT0_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_gmem_in0_ARADDR[63:0],m_axi_gmem_in0_ARBURST[1:0],m_axi_gmem_in0_ARCACHE[3:0],m_axi_gmem_in0_ARID[0:0],m_axi_gmem_in0_ARLEN[7:0],m_axi_gmem_in0_ARLOCK[1:0],m_axi_gmem_in0_ARPROT[2:0],m_axi_gmem_in0_ARQOS[3:0],m_axi_gmem_in0_ARREADY,m_axi_gmem_in0_ARREGION[3:0],m_axi_gmem_in0_ARSIZE[2:0],m_axi_gmem_in0_ARVALID,m_axi_gmem_in0_AWADDR[63:0],m_axi_gmem_in0_AWBURST[1:0],m_axi_gmem_in0_AWCACHE[3:0],m_axi_gmem_in0_AWID[0:0],m_axi_gmem_in0_AWLEN[7:0],m_axi_gmem_in0_AWLOCK[1:0],m_axi_gmem_in0_AWPROT[2:0],m_axi_gmem_in0_AWQOS[3:0],m_axi_gmem_in0_AWREADY,m_axi_gmem_in0_AWREGION[3:0],m_axi_gmem_in0_AWSIZE[2:0],m_axi_gmem_in0_AWVALID,m_axi_gmem_in0_BID[0:0],m_axi_gmem_in0_BREADY,m_axi_gmem_in0_BRESP[1:0],m_axi_gmem_in0_BVALID,m_axi_gmem_in0_RDATA[31:0],m_axi_gmem_in0_RID[0:0],m_axi_gmem_in0_RLAST,m_axi_gmem_in0_RREADY,m_axi_gmem_in0_RRESP[1:0],m_axi_gmem_in0_RVALID,m_axi_gmem_in0_WDATA[31:0],m_axi_gmem_in0_WID[0:0],m_axi_gmem_in0_WLAST,m_axi_gmem_in0_WREADY,m_axi_gmem_in0_WSTRB[3:0],m_axi_gmem_in0_WVALID,m_axi_gmem_out0_ARADDR[63:0],m_axi_gmem_out0_ARBURST[1:0],m_axi_gmem_out0_ARCACHE[3:0],m_axi_gmem_out0_ARID[0:0],m_axi_gmem_out0_ARLEN[7:0],m_axi_gmem_out0_ARLOCK[1:0],m_axi_gmem_out0_ARPROT[2:0],m_axi_gmem_out0_ARQOS[3:0],m_axi_gmem_out0_ARREADY,m_axi_gmem_out0_ARREGION[3:0],m_axi_gmem_out0_ARSIZE[2:0],m_axi_gmem_out0_ARVALID,m_axi_gmem_out0_AWADDR[63:0],m_axi_gmem_out0_AWBURST[1:0],m_axi_gmem_out0_AWCACHE[3:0],m_axi_gmem_out0_AWID[0:0],m_axi_gmem_out0_AWLEN[7:0],m_axi_gmem_out0_AWLOCK[1:0],m_axi_gmem_out0_AWPROT[2:0],m_axi_gmem_out0_AWQOS[3:0],m_axi_gmem_out0_AWREADY,m_axi_gmem_out0_AWREGION[3:0],m_axi_gmem_out0_AWSIZE[2:0],m_axi_gmem_out0_AWVALID,m_axi_gmem_out0_BID[0:0],m_axi_gmem_out0_BREADY,m_axi_gmem_out0_BRESP[1:0],m_axi_gmem_out0_BVALID,m_axi_gmem_out0_RDATA[31:0],m_axi_gmem_out0_RID[0:0],m_axi_gmem_out0_RLAST,m_axi_gmem_out0_RREADY,m_axi_gmem_out0_RRESP[1:0],m_axi_gmem_out0_RVALID,m_axi_gmem_out0_WDATA[31:0],m_axi_gmem_out0_WID[0:0],m_axi_gmem_out0_WLAST,m_axi_gmem_out0_WREADY,m_axi_gmem_out0_WSTRB[3:0],m_axi_gmem_out0_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 99999001, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN vitis_design_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_gmem_in0:m_axi_gmem_out0, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 99999001, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN vitis_design_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_in0_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_in0_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_in0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 99999001, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN vitis_design_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_in0_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_in0 WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_out0_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_out0_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_out0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 99999001, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN vitis_design_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_out0_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_out0 WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "myproject_axi_master,Vivado 2025.2";
begin
end;
