<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName></userIPName>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s</name>
      <module_structure>Sequential</module_structure>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>layer3_out</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>res</originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>80</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>stream_in0_input_layer_1</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>13</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>17</id>
              <name>indvar_flatten</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>43</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>23</id>
              <name>indvar_flatten_write_ln0</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>45</item>
            <item>46</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.42</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>24</id>
              <name>br_ln25</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>25</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>2</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>25</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>47</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>26</id>
              <name>indvar_flatten_load</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>25</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>25</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>59</item>
            <item>216</item>
          </oprand_edges>
          <opcode>load</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>27</id>
              <name>icmp_ln25</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>25</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>25</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>icmp_ln25_fu_119_p2</rtlName>
              <control>auto</control>
              <opType>seteq</opType>
              <implIndex>auto</implIndex>
              <coreName>Cmp</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>9</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>60</item>
            <item>62</item>
          </oprand_edges>
          <opcode>icmp</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.78</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>28</id>
              <name>add_ln25</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>25</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>25</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>add_ln25_fu_125_p2</rtlName>
              <control>auto</control>
              <opType>add</opType>
              <implIndex>fabric</implIndex>
              <coreName>Adder</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>63</item>
            <item>65</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.78</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>29</id>
              <name>br_ln25</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>25</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>25</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>66</item>
            <item>67</item>
            <item>68</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>7</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>34</id>
              <name>stream_in0_input_layer_1_read</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>32</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>32</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>srl</implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>80</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>49</item>
            <item>50</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>2.18</m_delay>
          <m_topoIndex>10</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>35</id>
              <name>trunc_ln32</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>32</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>32</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76_in_elem_0_0_0_0_0_val</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>51</item>
          </oprand_edges>
          <opcode>trunc</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>11</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>36</id>
              <name>_ln32</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>32</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>32</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76</rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>17</count>
            <item_version>0</item_version>
            <item>53</item>
            <item>54</item>
            <item>55</item>
            <item>69</item>
            <item>70</item>
            <item>71</item>
            <item>72</item>
            <item>73</item>
            <item>74</item>
            <item>75</item>
            <item>76</item>
            <item>77</item>
            <item>78</item>
            <item>79</item>
            <item>80</item>
            <item>81</item>
            <item>82</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>12</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>37</id>
              <name>indvar_flatten_write_ln25</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>25</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>25</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>56</item>
            <item>57</item>
            <item>217</item>
            <item>218</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.42</m_delay>
          <m_topoIndex>8</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>38</id>
              <name>br_ln27</name>
              <fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
              <fileDirectory>../../../.</fileDirectory>
              <lineNumber>27</lineNumber>
              <contextFuncName>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</contextFuncName>
              <contextNormFuncName>conv_2d_buffer_latency_cl_nnet_array_ap_ufixed_1_1_ap_q_mode_0_ap_o_mode_3_0_1U_nnet_array_ap_ufixed_5_5_ap_q_mode_5_ap_o_mode_3_0_16U_config3_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ncgadmin/Bachelor/HLS4ML_testbench_KV260/development/MNIST_CNN/1/hls4ml_prj_mnist_hls4ml_VU</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_buffer_latency_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>27</second>
                    </item>
                    <item>
                      <first>
                        <first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
                        <second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;1, 1, (ap_q_mode)0, (ap_o_mode)3, 0&amp;gt;, 1U&amp;gt;, nnet::array&amp;lt;ap_ufixed&amp;lt;5, 5, (ap_q_mode)5, (ap_o_mode)3, 0&amp;gt;, 16U&amp;gt;, config3&amp;gt;</second>
                      </first>
                      <second>76</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>58</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>13</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>40</id>
              <name>_ln0</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.42</m_delay>
          <m_topoIndex>9</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_16">
          <Value>
            <Obj>
              <type>2</type>
              <id>42</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_17">
          <Value>
            <Obj>
              <type>2</type>
              <id>44</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_18">
          <Value>
            <Obj>
              <type>2</type>
              <id>52</id>
              <name>compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:compute_output_buffer_2d&lt;array,array&lt;ap_ufixed&lt;5,5,5,3,0&gt;,16u&gt;,config3&gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_19">
          <Value>
            <Obj>
              <type>2</type>
              <id>61</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>784</content>
        </item>
        <item class_id_reference="16" object_id="_20">
          <Value>
            <Obj>
              <type>2</type>
              <id>64</id>
              <name>empty</name>
              <fileName></fileName>
              <fileDirectory></fileDirectory>
              <lineNumber>0</lineNumber>
              <contextFuncName></contextFuncName>
              <contextNormFuncName></contextNormFuncName>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName></originalName>
              <rtlName></rtlName>
              <control></control>
              <opType></opType>
              <implIndex></implIndex>
              <coreName></coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>4294967295</coreId>
              <rtlModuleName></rtlModuleName>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_21">
          <Obj>
            <type>3</type>
            <id>25</id>
            <name>entry</name>
            <fileName></fileName>
            <fileDirectory></fileDirectory>
            <lineNumber>0</lineNumber>
            <contextFuncName></contextFuncName>
            <contextNormFuncName></contextNormFuncName>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName></originalName>
            <rtlName></rtlName>
            <control></control>
            <opType></opType>
            <implIndex></implIndex>
            <coreName></coreName>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>4294967295</coreId>
            <rtlModuleName></rtlModuleName>
          </Obj>
          <node_objs>
            <count>3</count>
            <item_version>0</item_version>
            <item>17</item>
            <item>23</item>
            <item>24</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_22">
          <Obj>
            <type>3</type>
            <id>30</id>
            <name>for.body12.i.i</name>
            <fileName></fileName>
            <fileDirectory></fileDirectory>
            <lineNumber>0</lineNumber>
            <contextFuncName></contextFuncName>
            <contextNormFuncName></contextNormFuncName>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName></originalName>
            <rtlName></rtlName>
            <control></control>
            <opType></opType>
            <implIndex></implIndex>
            <coreName></coreName>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>4294967295</coreId>
            <rtlModuleName></rtlModuleName>
          </Obj>
          <node_objs>
            <count>4</count>
            <item_version>0</item_version>
            <item>26</item>
            <item>27</item>
            <item>28</item>
            <item>29</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_23">
          <Obj>
            <type>3</type>
            <id>39</id>
            <name>for.cond.cleanup11.i.i</name>
            <fileName></fileName>
            <fileDirectory></fileDirectory>
            <lineNumber>0</lineNumber>
            <contextFuncName></contextFuncName>
            <contextNormFuncName></contextNormFuncName>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName></originalName>
            <rtlName></rtlName>
            <control></control>
            <opType></opType>
            <implIndex></implIndex>
            <coreName></coreName>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>4294967295</coreId>
            <rtlModuleName></rtlModuleName>
          </Obj>
          <node_objs>
            <count>5</count>
            <item_version>0</item_version>
            <item>34</item>
            <item>35</item>
            <item>36</item>
            <item>37</item>
            <item>38</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_24">
          <Obj>
            <type>3</type>
            <id>41</id>
            <name>conv_2d_cl&lt;array&lt;ap_ufixed&lt;1, 1, 0, 3, 0&gt;, 1u&gt;, array&lt;ap_ufixed&lt;5, 5, 5, 3, 0&gt;, 16u&gt;, config3&gt;.exit</name>
            <fileName></fileName>
            <fileDirectory></fileDirectory>
            <lineNumber>0</lineNumber>
            <contextFuncName></contextFuncName>
            <contextNormFuncName></contextNormFuncName>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName></originalName>
            <rtlName></rtlName>
            <control></control>
            <opType></opType>
            <implIndex></implIndex>
            <coreName></coreName>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>4294967295</coreId>
            <rtlModuleName></rtlModuleName>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>40</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>41</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_25">
          <id>43</id>
          <edge_type>1</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>17</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>45</id>
          <edge_type>1</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>23</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>46</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>23</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>47</id>
          <edge_type>2</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>24</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>50</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>34</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>51</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>35</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>53</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>54</id>
          <edge_type>1</edge_type>
          <source_obj>35</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>55</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>56</id>
          <edge_type>1</edge_type>
          <source_obj>28</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>57</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>58</id>
          <edge_type>2</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>38</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>59</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>26</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>60</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>27</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>62</id>
          <edge_type>1</edge_type>
          <source_obj>61</source_obj>
          <sink_obj>27</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>63</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>28</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>65</id>
          <edge_type>1</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>28</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>66</id>
          <edge_type>1</edge_type>
          <source_obj>27</source_obj>
          <sink_obj>29</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>67</id>
          <edge_type>2</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>29</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>68</id>
          <edge_type>2</edge_type>
          <source_obj>41</source_obj>
          <sink_obj>29</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>69</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>70</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>71</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>72</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>73</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>75</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>76</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>77</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>78</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>80</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>81</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>82</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>212</id>
          <edge_type>2</edge_type>
          <source_obj>25</source_obj>
          <sink_obj>30</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>213</id>
          <edge_type>2</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>41</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>214</id>
          <edge_type>2</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>39</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>215</id>
          <edge_type>2</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>30</sink_obj>
          <is_back_edge>1</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>216</id>
          <edge_type>4</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>26</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>217</id>
          <edge_type>4</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>218</id>
          <edge_type>4</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>37</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_66">
        <mId>1</mId>
        <mTag>conv_2d_cl&lt;array&lt;ap_ufixed,1u&gt;,array&lt;ap_ufixed&lt;5,5,5,3,0&gt;,16u&gt;,config3&gt;</mTag>
        <mNormTag>conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>3</count>
          <item_version>0</item_version>
          <item>2</item>
          <item>3</item>
          <item>4</item>
        </sub_regions>
        <basic_blocks>
          <count>0</count>
          <item_version>0</item_version>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>2354</mMinLatency>
        <mMaxLatency>2354</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"></mDfPipe>
      </item>
      <item class_id_reference="22" object_id="_67">
        <mId>2</mId>
        <mTag>Entry</mTag>
        <mNormTag>Entry</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>25</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>0</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"></mDfPipe>
      </item>
      <item class_id_reference="22" object_id="_68">
        <mId>3</mId>
        <mTag>ReadInputHeight_ReadInputWidth</mTag>
        <mNormTag>ReadInputHeight_ReadInputWidth</mNormTag>
        <mType>1</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>30</item>
          <item>39</item>
        </basic_blocks>
        <mII>3</mII>
        <mDepth>3</mDepth>
        <mMinTripCount>784</mMinTripCount>
        <mMaxTripCount>784</mMaxTripCount>
        <mMinLatency>2352</mMinLatency>
        <mMaxLatency>2352</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"></mDfPipe>
      </item>
      <item class_id_reference="22" object_id="_69">
        <mId>4</mId>
        <mTag>Return</mTag>
        <mNormTag>Return</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>41</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>0</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"></mDfPipe>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_70">
      <states class_id="25" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_71">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>14</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_72">
              <id>17</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_73">
              <id>18</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_74">
              <id>19</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_75">
              <id>20</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_76">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_77">
              <id>22</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_78">
              <id>23</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_79">
              <id>24</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_80">
              <id>26</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_81">
              <id>27</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_82">
              <id>28</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_83">
              <id>29</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_84">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_85">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_86">
          <id>2</id>
          <operations>
            <count>3</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_87">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_88">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_89">
              <id>36</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_90">
          <id>3</id>
          <operations>
            <count>5</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_91">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_92">
              <id>32</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_93">
              <id>33</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_94">
              <id>36</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
            <item class_id_reference="28" object_id="_95">
              <id>38</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_96">
          <inState>2</inState>
          <outState>3</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_97">
          <inState>1</inState>
          <outState>2</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="34" tracking_level="1" version="0" object_id="_98">
      <dp_component_resource class_id="35" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>flow_control_loop_pipe_U (myproject_axi_master_flow_control_loop_pipe)</first>
          <second class_id="37" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76 (compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="0" version="0">
              <first>FF</first>
              <second>397</second>
            </item>
            <item>
              <first>LUT</first>
              <second>764</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>add_ln25_fu_125_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>10</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>17</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_block_state1_pp0_stage0_iter0 ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>icmp_ln25_fu_119_p2 ( icmp ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>10</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>9</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>17</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>7</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>4</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>4</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>20</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_int</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_sig_allocacmp_indvar_flatten_load</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>10</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>20</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>indvar_flatten_fu_66</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>10</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>20</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer3_out_blk_n</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>real_start</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>stream_in0_input_layer_1_blk_n</first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>5</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>3</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>3</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76_ap_start_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>indvar_flatten_fu_66</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>10</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>10</second>
            </item>
          </second>
        </item>
        <item>
          <first>start_once_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>flow_control_loop_pipe_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="39" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="0" version="0">
          <first>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76 (compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>36</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>add_ln25_fu_125_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>28</item>
          </second>
        </item>
        <item>
          <first>icmp_ln25_fu_119_p2 ( icmp ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>27</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="41" tracking_level="0" version="0">
      <count>13</count>
      <item_version>0</item_version>
      <item class_id="42" tracking_level="0" version="0">
        <first>17</first>
        <second class_id="43" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>23</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>24</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>26</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>27</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>28</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>29</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>34</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>35</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>37</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>38</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>40</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="44" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>25</first>
        <second class_id="46" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>30</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <first>1</first>
          <second>3</second>
        </second>
      </item>
      <item>
        <first>41</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="47" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="48" tracking_level="1" version="0" object_id="_99">
        <region_name>ReadInputHeight_ReadInputWidth</region_name>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>30</item>
          <item>39</item>
        </basic_blocks>
        <nodes>
          <count>0</count>
          <item_version>0</item_version>
        </nodes>
        <anchor_node>-1</anchor_node>
        <region_type>8</region_type>
        <interval>3</interval>
        <pipe_depth>3</pipe_depth>
        <mDBIIViolationVec class_id="49" tracking_level="0" version="0">
          <count>0</count>
          <item_version>0</item_version>
        </mDBIIViolationVec>
      </item>
    </regions>
    <dp_fu_nodes class_id="50" tracking_level="0" version="0">
      <count>9</count>
      <item_version>0</item_version>
      <item class_id="51" tracking_level="0" version="0">
        <first>66</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>70</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>76</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>36</item>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>111</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>23</item>
        </second>
      </item>
      <item>
        <first>116</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>26</item>
        </second>
      </item>
      <item>
        <first>119</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>27</item>
        </second>
      </item>
      <item>
        <first>125</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>28</item>
        </second>
      </item>
      <item>
        <first>131</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>37</item>
        </second>
      </item>
      <item>
        <first>136</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>35</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="53" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="54" tracking_level="0" version="0">
        <first>add_ln25_fu_125</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>28</item>
        </second>
      </item>
      <item>
        <first>icmp_ln25_fu_119</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>27</item>
        </second>
      </item>
      <item>
        <first>indvar_flatten_fu_66</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>trunc_ln32_fu_136</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>35</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_76</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>36</item>
          <item>36</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>4</count>
      <item_version>0</item_version>
      <item>
        <first>indvar_flatten_load_load_fu_116</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>26</item>
        </second>
      </item>
      <item>
        <first>store_ln0_store_fu_111</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>23</item>
        </second>
      </item>
      <item>
        <first>store_ln25_store_fu_131</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>37</item>
        </second>
      </item>
      <item>
        <first>stream_in0_input_layer_1_read_read_fu_70</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="55" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="56" tracking_level="0" version="0">
        <first class_id="57" tracking_level="0" version="0">
          <first>void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>141</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>indvar_flatten_reg_141</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="58" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="59" tracking_level="0" version="0">
        <first>layer3_out</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>36</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>stream_in0_input_layer_1</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>34</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>2</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
    </port2core>
    <node2core>
      <count>4</count>
      <item_version>0</item_version>
      <item>
        <first>27</first>
        <second>
          <first>526</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>28</first>
        <second>
          <first>8</first>
          <second>4</second>
        </second>
      </item>
      <item>
        <first>34</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
    </node2core>
    <sched_res class_id="60" tracking_level="1" version="0" object_id="_100">
      <ResourceTableActual class_id="61" tracking_level="0" version="0">
        <II>16</II>
      </ResourceTableActual>
      <ResourceTableFailed class_id="62" tracking_level="0" version="0">
        <II>-1</II>
      </ResourceTableFailed>
    </sched_res>
  </syndb>
</boost_serialization>
